descriptDict = {
                'CSCI1103': 'Java Programming MN West', 
                'CSCI1901': 'Computer Programming I',
                'CSCI1902': 'Computer Programming 2',
                'CSCI2011': 'Discrete Structures of Computer Science',
                'CSCI2011-evening': 'Discrete Structures of Computer Science',
                'CSCI2041': 'Advanced Programming Principles',
                'CSCI3081': 'Program Design and Development',
                'CSCI4011': 'Formal Languages and Automata Theory',
                'CSCI4041': 'Algorithms and Data Structures',
                'CSCI4041H':'Honors Algorithms and Data Structures',
                'CSCI4061': 'Intro to Operating Systems',
                'CSCI4131': 'Internet Programming',
                'CSCI4211': 'Introduction to Computer Networks',
                'CSCI4511W': 'Introduction to Artificial Intelligence',
                'CSCI4707': 'Principles of Database Systems',
                'CSCI5103': 'Operating Systems',
                'CSCI5106': 'Programming Languages',
                'CSCI5115': 'User Interface Design, Implementation and Evaluation',
                'CSCI5271': 'Introduction to Computer Security',
                'CSCI5304': 'Computational Aspects of Matrix Theory',
                'CSCI5421': 'Advanced Algorithms and Data Structures',
                'CSCI5511': 'Artificial Intelligence I',
                'CSCI5523': 'Introduction to Data Mining',
                'CSCI5525': 'Machine Learning',
                'CSCI5801': 'Software Engineering I',
                'CSCI5980-002': 'Topics in Computer Science: Distributed Computing',
                'CSCI5980-sf': 'Software Foundations',
                'CSCI8970': 'Computer Science Colloquium',
                'CSCI8980-sf': 'Software Foundations',
                'CSCI8980-vr': 'Current Research in Virtual and Augmented Reality',
}
